FROM devopsedu/webapp

WORKDIR /var/www/html

# Copy the current directory contents into the container at /var/www/html
COPY . /var/www/html

# Expose port 80 to allow external connections to the container
EXPOSE 80
